version: "3"
services:
  nginx:
    depends_on: 
      - app
    image: nginx:1.17-alpine
    container_name: seaniadmin-nginx
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./seaniadmin:/var/www
      - ./seaniadmin/public/storage:/var/www/public/storage
      - ./nginx:/etc/nginx/conf.d
    networks:
      - seaniadmin-network

  db:
    image: mysql:5.7.22
    container_name: seaniadmin-db
    restart: unless-stopped
    command: mysqld --sql_mode=""
    tty: true
    ports:
      - "3086:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    networks:
      - seaniadmin-network
    volumes:
      - dbdata:/var/lib/mysql

  app:
    depends_on:
      - db
    build:
      args:
        user: avatardev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: seaniadmin
    container_name: seaniadmin-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./seaniadmin:/var/www
    networks:
      - seaniadmin-network

networks:
  seaniadmin-network:

volumes:
  dbdata:
    driver: local