version: "3"
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: seaniadmin2-nginx
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./seaniadmin:/var/www
      - ./seaniadmin/public/storage:/var/www/public/storage
      - ./nginx:/etc/nginx/conf.d
    networks: 
      - opennetwork

networks:
  opennetwork:
    external: true