version: "3"
services:
  nginx:
    depends_on: 
      - app
    image: nginx:1.17-alpine
    container_name: seanibackend-nginx
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./seanibackend:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - opennetwork

  db:
    image: mysql:5.7.22
    container_name: seanibackend-db
    restart: unless-stopped
    command: mysqld --sql_mode=""
    tty: true
    ports:
      - "3086:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    networks:
      - opennetwork
    volumes:
      - dbdata:/var/lib/mysql

  app:
    depends_on:
      - db
    build:
      args:
        user: avatardev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: seanibackend
    container_name: seanibackend-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./seanibackend:/var/www
    networks:
      - opennetwork

networks:
  opennetwork:
    external: true

volumes:
  dbdata:
    driver: local