version: "3"
services:
  nginx:
    depends_on: 
      - app
    image: nginx:1.17-alpine
    container_name: seaniadmin-nginx
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./seaniadmin:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - opennetwork

  
  app:
    build:
      args:
        user: avatardev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: seaniadmin
    container_name: seaniadmin-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./seaniadmin:/var/www
    networks:
      - opennetwork

networks:
  opennetwork:
    external: true

volumes:
  dbdata:
    driver: local