version: "3"
services:
  nginx:
    depends_on: 
      - app2
    image: nginx:1.17-alpine
    container_name: seanibackend2-nginx
    restart: unless-stopped
    ports:
      - 1000:80
    volumes:
      - ./seanibackend:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - opennetwork

  
  app2:
    build:
      args:
        user: avatardev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: seanibackend
    container_name: seanibackend2-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./seanibackend:/var/www
    networks:
      - opennetwork

networks:
  opennetwork:
    external: true

volumes:
  dbdata:
    driver: local